### PR TITLE
Refactor/rename disqualified

### PR DESCRIPTION
**Pull request by IanFonzie**
This PR closes issue: [DMM-131]

Includes tests? [N]
Updated docs? [N]

Proposed changes:
- Rename disqualified labels to non-compliant
- Remove disqualification language from email templates

Additional notes:
- Modified email language provided by Jason Taylor

### CODE REVIEW

**Review by SteveChapmanBCDX — COMMENTED** [review]
@IanFonzie - Did you review the word choice with Jason?  If not, we should get his eyes on this.

**Comment by IanFonzie** [comment]
> @IanFonzie - Did you review the word choice with Jason? If not, we should get his eyes on this.

Yup, he helped write it

**Review by SteveChapmanBCDX — APPROVED** [review]
Reviewed and approved.

**Comment by SteveChapmanBCDX** [comment]
Merge approved.

**Pull request merged**
