### PR TITLE
DM-97 Extend opportunity and proposal histories to support general notes and file uploads for record-keeping

### PR DESCRIPTION
**Pull request by sutherlanda**
This PR includes the back-end changes in support of DM-97.

Summary of changes:

* Add DB migration for adding new event type to opportunity and proposal statuses (NoteAdded), and for creating relationship tables for associating file attachments and status/events.
* Modify update ADTs on both CWU/SWU opportunities and proposals to allow adding of notes with attachments.
* Update permissions and validation.
* Front-end was modified to account for updates to shared libraries, but still needs the associated UIs added.

Note: The previous PRs for DM-232 and DM-29 should be merged first, as the DB migration in this PR depends on migrations in those branches.

### CODE REVIEW

**Comment by sutherlanda** [comment]
Note: Migrations for this PR will need to be redone prior to merging.

**Comment by dhruvio** [comment]
On hold until budget is available to continue with this feature.

**Comment by SteveChapmanBCDX** [comment]
Closing (and not merging) this PR.  This PR history was used to inform development of Issue #203.

**Comment by mikevespi** [comment]
Work migrated to #140. Closing this issue.

**Pull request closed without merging**
