### PR TITLE
DM-1119 Ensure framework.component.cmd.makeDebouncedDispatch is working correctly

### PR DESCRIPTION
**Pull request by dhruvio**
This PR closes issue: DM-1119

Includes tests? Y
Updated docs? N

Proposed changes:
- Refactor the `makeDebouncedDispatch` function to ensure it works as intended.
- Write unit tests for `makeDebouncedDispatch`.
- Add the `sinon` and `@types/sinon` development dependencies.

### CODE REVIEW

**Review by bdolor — CHANGES_REQUESTED** [review]
Recommend adding standardized doc comments.

TSDoc compliant doc blocks could include: 

- `@example` ref: https://tsdoc.org/pages/tags/example/ 
- `@remarks` ref: https://tsdoc.org/pages/tags/remarks/ 
- `@param` ref: https://tsdoc.org/pages/tags/param/
- `@see` ref: https://tsdoc.org/pages/tags/see/

**Comment by bdolor** [comment]
@dhruvio would you be willing to take a look at this soon?

**Comment by dhruvio** [comment]
@bdolor Can I do  the docs in a separate PR? I have limited time each week, and don't want to block the fix from going to production.

**Comment by bdolor** [comment]
> @bdolor Can I do the docs in a separate PR? I have limited time each week, and don't want to block the fix from going to production.

Separating documentation from the work risks not getting prioritized and given the history, preference is to advocate for it to be part of a definition of done going forward.

**Pull request merged**
